export { Comment } from './lib/comment-handler';
export { VERSION } from './lib/core';
export { FormatOptions, generate, GenerateOptions, MozillaOptions } from './lib/escodegen';
export { parse, ParseDelegate, parseModule, ParseOptions, parseScript, tokenize } from './lib/esprima';
export { generateRandomId } from './lib/generateRandomId';
export { getLoopProtectorBlocks } from './lib/getLoopProtectorBlocks';
export { INode } from './lib/INode';
export { MetaData } from './lib/MetaData';
export {
    ArgumentListElement,
    ArrayExpression,
    ArrayExpressionElement,
    ArrayPattern,
    ArrayPatternElement,
    ArrowFunctionExpression,
    AssignmentExpression,
    AssignmentPattern,
    AsyncArrowFunctionExpression,
    AsyncFunctionDeclaration,
    AsyncFunctionExpression,
    AwaitExpression,
    BaseNode,
    BaseNodeWithoutComments,
    BinaryExpression,
    BinaryOperator,
    BindingIdentifier,
    BindingPattern,
    BlockStatement,
    BreakStatement,
    CallExpression,
    CatchClause,
    ClassBody,
    ClassDeclaration,
    ClassExpression,
    ComputedMemberExpression,
    ConditionalExpression,
    ContinueStatement,
    DebuggerStatement,
    Declaration,
    Directive,
    DoWhileStatement,
    EmptyStatement,
    ExportableDefaultDeclaration,
    ExportableNamedDeclaration,
    ExportAllDeclaration,
    ExportDeclaration,
    ExportDefaultDeclaration,
    ExportNamedDeclaration,
    ExportSpecifier,
    Expression,
    ExpressionStatement,
    ForInStatement,
    ForOfStatement,
    ForStatement,
    FunctionDeclaration,
    FunctionExpression,
    FunctionParameter,
    Identifier,
    IfStatement,
    Import,
    ImportDeclaration,
    ImportDeclarationSpecifier,
    ImportDefaultSpecifier,
    ImportNamespaceSpecifier,
    ImportSpecifier,
    LabeledStatement,
    Literal,
    MetaProperty,
    MethodDefinition,
    Module,
    NewExpression,
    ObjectExpression,
    ObjectExpressionProperty,
    ObjectPattern,
    ObjectPatternProperty,
    Property,
    PropertyKey,
    PropertyValue,
    RegexLiteral,
    RestElement,
    RestProperty,
    ReturnStatement,
    Script,
    SequenceExpression,
    SpreadElement,
    SpreadProperty,
    Statement,
    StatementListItem,
    StaticMemberExpression,
    Super,
    SwitchCase,
    SwitchStatement,
    TaggedTemplateExpression,
    TemplateElement,
    TemplateElementValue,
    TemplateLiteral,
    ThisExpression,
    ThrowStatement,
    TryStatement,
    UnaryExpression,
    UpdateExpression,
    UpdateOperator,
    VariableDeclaration,
    VariableDeclarator,
    WhileStatement,
    WithStatement,
    YieldExpression
} from './lib/nodes';
export { Syntax } from './lib/syntax';
export { Config } from './lib/tokenizer';

